### ISSUE TITLE
Add package.json to make installable from NPM

### ISSUE THREAD

**Issue by bryanjhv** [Jeija/QRScanJS#4]
Given that [Bower is dead](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) and as such more and more people is uploading its frontend packages to NPM, it might be a good idea to also do that with this useful library.

The request is also because I tried using it by adding a tagged version to my `package.json` but NPM complains there is no `package.json` at that repository, producing an error like the one shown in the attached capture.

![Capture](https://user-images.githubusercontent.com/2767941/37562002-1fb6a946-2a2b-11e8-9fdf-349ef939484f.png)

Maybe an easy and quick solution is just to copy `bower.json` (you don't even need to publish the package to the NPM repository, it's fine as it is).

Thanks in advance!

**Comment by Jeija** [comment]
Sorry for the late answer! As you suggested, I just did `cp bower.json package.json`. I hope this solves your issue. If there is something else I need to do, feel free to reopen this issue.

**Comment by bryanjhv** [comment]
It works as expected, many thanks both for solving the issue and for your useful work on this library.

For reference, I got it working with this `package.json`:
```json
{
  "dependencies": {
    "qrscanjs": "Jeija/QRScanJS#d9d2d0b988"
  }
}
```
